substitutions:
  _REGION: europe-west1
  _REPOSITORY: manhwa

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile.api
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/manhwa-api:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile.cloudrun-worker
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/manhwa-worker:latest
      - .

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/manhwa-api:latest
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/manhwa-worker:latest

timeout: 3600s
