services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: manhwa-backend-local
    env_file:
      - .env
    environment:
      - PIPELINE_EXECUTION_MODE=local
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
