FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1 \
    PORT=8080

WORKDIR /app

COPY requirements-api.txt ./
RUN pip install --no-cache-dir -r requirements-api.txt

COPY api ./api
COPY core ./core
COPY db ./db
COPY main.py ./

CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port ${PORT}"]
