services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: manhwa-api-local
    env_file:
      - .env
    environment:
      - PIPELINE_EXECUTION_MODE=local
      - PORT=8000
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
